### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by glebfox** [ilushaaa/jmix-hw-advanced-data-manipulation#1]
`<column id="countdownDays" caption="msg://countdownDays.caption"/>` - no need to define caption for column, since `countdownDays` is an attribute of an entity it can and must have localized message as any other attributes. 

----

`com.sample.hotel.app.BookingService#reserveRoom` - method returns created entity (new) instead of saved by `DataManager` (detached). 

----

`BookingService#cancelReservation` has incorect implementation.
1. invoking the `cancel` action doesn't refresh changed item, i.e. prev status is displayed (commented code in the `cancelBooking` provided by the homework template method is correct)
2. The task says that: `Для реализации используйте слушатель события EntityChangedEvent.`

**Comment by ilushaaa** [comment]
Fixed in the latest commit.
